'use strict';
/* Ashford: deterministic, LLM-free, event-sourced social simulation. */
const Ashford=(()=>{
const NAMES=['Thomas','Henry','Mary','Eleanor','Arthur','Clara','Samuel','Rose','George','Alice','Oliver','Nora','Edith','James','Martha','William','Ada','Edward','Florence','Walter','Iris','Peter','Lucy','Daniel','Grace','Robert'];
const SURNAMES=['Miller','Collins','Bennett','Walker','Reed','Cooper','Hart','Turner','Wells','Baker'];
const JOBS=['Demirci','Çiftçi','Eczacı','Fırıncı','Bankacı','Terzi','Çırak','Saloon işletmecisi','Öğretmen','Marangoz','Tüccar','İşçi'];
const PLACES=['Ev','Meydan','Saloon','Fırın','Demirci','Çiftlik','Eczane','Banka','Okul','Pazar'];
const LIMIT=5000, MEMORY=65;
const clamp=(x,a=0,b=100)=>Math.max(a,Math.min(b,x));
function rng(w){w.seed=(Math.imul(w.seed,1664525)+1013904223)>>>0;return w.seed/4294967296}
function roll(w,p){return rng(w)<clamp(p,0,1)}
function pick(w,a){return a[Math.floor(rng(w)*a.length)]}
function pair(a,b){return a.id<b.id?`${a.id}:${b.id}`:`${b.id}:${a.id}`}
function relation(w,a,b){const k=pair(a,b);return w.relations[k]||(w.relations[k]={trust:40,affinity:40,conflict:0,history:[]})}
function changeRel(w,a,b,trust=0,affinity=0,conflict=0,eventId=null){if(a.id===b.id)return;const r=relation(w,a,b);r.trust=clamp(r.trust+trust);r.affinity=clamp(r.affinity+affinity);r.conflict=clamp(r.conflict+conflict);if(eventId!==null){r.history.push(eventId);if(r.history.length>35)r.history.shift()}}
function addEvent(w,type,actors,details={},witnesses=actors){const e={id:w.nextEvent++,day:w.day,hour:w.hour,type,actors:actors.map(n=>n.id),details};w.events.push(e);for(const n of witnesses)learn(w,n,e,'witness',null);if(w.events.length>LIMIT){const gone=w.events.shift();for(const n of w.people)n.memory=n.memory.filter(m=>m.eventId!==gone.id);if(w.playerKnowledge)w.playerKnowledge=w.playerKnowledge.filter(id=>id!==gone.id)}return e}
function learn(w,n,e,source='heard',from=null){if(!n||!e)return false;const old=n.memory.find(m=>m.eventId===e.id);if(old){if(source==='witness'){old.source='witness';old.from=null}return false}n.memory.unshift({eventId:e.id,source,from,day:w.day,importance:importance(w,n,e)});n.memory.sort((a,b)=>b.importance-a.importance||b.day-a.day);if(n.memory.length>MEMORY)n.memory.length=MEMORY;return true}
function importance(w,n,e){let v=18;if(e.actors.includes(n.id))v+=45;for(const id of e.actors)if(id!==n.id&&n.family.includes(id))v+=20;if(['death','birth','marriage','inheritance','bankruptcy','conflict','loan','secret'].includes(e.type))v+=17;return clamp(v)}
function person(w,id){return w.people.find(n=>n.id===id)}
function name(w,id){return person(w,id)?.name||'Bilinmeyen'}
function textEvent(w,e){if(!e)return 'Bilinmeyen olay';const a=name(w,e.actors[0]),b=name(w,e.actors[1]);const d=e.details;switch(e.type){case 'birth':return `${a} ailesine yeni bir çocuk katıldı: ${b}.`;case 'death':return `${a} hayatını kaybetti.`;case 'marriage':return `${a} ile ${b} evlendi.`;case 'inheritance':return `${a} ile ${b} miras konusunda anlaşmazlık yaşadı.`;case 'loan':return `${b}, ${a} adlı kişiye ${d.amount}$ borç verdi.`;case 'repayment':return `${a}, ${b} adlı kişiye ${d.amount}$ geri ödedi.`;case 'help':return d.player?`Oyuncu, ${a} adlı kişiye ${d.amount}$ yardım etti.`:`${a}, ${b} adlı kişiye yardım etti.`;case 'refusal':return `${b}, ${a} adlı kişinin yardım isteğini reddetti.`;case 'conflict':return `${a} ile ${b} tartıştı.`;case 'friendship':return `${a} ile ${b} yakınlaştı.`;case 'gossip':return d.player?`Oyuncu, ${a} adlı kişiye bir haber aktardı.`:`${a}, ${b} ile bir haber paylaştı.`;case 'bankruptcy':return `${a} borçlarını ödeyemedi ve mülkünü kaybetti.`;case 'purchase':return `${a}, ${d.asset} satın aldı.`;case 'move':return `${a}, ${d.place} konumuna taşındı.`;case 'illness':return `${a} hastalandı.`;case 'recovery':return `${a} iyileşti.`;case 'work':return `${a} çalışarak ${d.amount}$ kazandı.`;case 'secret':return `${a} bir sırrını ${b} ile paylaştı.`;default:return `${a} ile ilgili bir olay yaşandı.`}}
function makePerson(w,id,first,last,age,job){const traits={pride:Math.floor(rng(w)*101),kindness:Math.floor(rng(w)*101),sociability:Math.floor(rng(w)*101),openness:Math.floor(rng(w)*101),discipline:Math.floor(rng(w)*101),risk:Math.floor(rng(w)*101)};return{id,name:`${first} ${last}`,first,last,age,job,alive:true,parents:[],partner:null,children:[],family:[],home:'Ev',place:'Ev',money:Math.floor(15+rng(w)*90),debt:0,creditor:null,assets:[],traits,needs:{hunger:15+Math.floor(rng(w)*30),energy:60+Math.floor(rng(w)*40),social:40+Math.floor(rng(w)*50),stress:Math.floor(rng(w)*25),health:85+Math.floor(rng(w)*16)},memory:[],lastAction:'Başlangıç',actionCounts:{},lastContact:{},birthDay:w.day-Math.round(age*365),goal:'',lastDialogue:null}}
function create(seed=12345,count=10){const w={version:10,seed:seed>>>0,initialSeed:seed>>>0,day:1,hour:8,nextId:0,nextEvent:0,people:[],events:[],relations:{},market:{food:3,wage:5,prosperity:55},metrics:{births:0,deaths:0,marriages:0,loans:0,rumors:0,decisions:0},lastNews:[],playerMoney:50,playerKnowledge:[],playerHelpDays:{}};for(let i=0;i<count;i++){const first=i<10?NAMES[i]:pick(w,NAMES),last=i<10?SURNAMES[[0,0,1,1,2,0,0,3,4,4][i]]:pick(w,SURNAMES),age=i<10?[46,43,32,27,51,42,19,35,58,24][i]:18+Math.floor(rng(w)*45),job=i<10?JOBS[[0,1,2,3,4,5,6,7,1,8][i]]:pick(w,JOBS);w.people.push(makePerson(w,w.nextId++,first,last,age,job))}const link=(i,j,type)=>{const a=w.people[i],b=w.people[j];if(!a||!b)return;a.family.push(b.id);b.family.push(a.id);changeRel(w,a,b,type==='dispute'?-22:35,type==='dispute'?-15:30,type==='dispute'?30:0)};link(0,1,'dispute');link(2,3,'sibling');link(0,5,'partner');link(0,6,'parent');link(5,6,'parent');link(8,9,'parent');w.people[0].partner=5;w.people[5].partner=0;w.people[0].children=[6];w.people[5].children=[6];w.people[6].parents=[0,5];w.people[8].children=[9];w.people[9].parents=[8];w.people[0].debt=120;w.people[0].creditor=4;w.people[4].money+=120;w.people[0].assets=['Demirci'];w.people[3].assets=['Fırın'];w.people[4].assets=['Banka'];w.people[7].assets=['Saloon'];const e=addEvent(w,'inheritance',[w.people[0],w.people[1]],{},[w.people[0],w.people[1]]);changeRel(w,w.people[0],w.people[1],-12,-5,12,e.id);for(let i=0;i<count;i++)for(let j=i+1;j<count;j++)if(roll(w,.12))changeRel(w,w.people[i],w.people[j],Math.floor(rng(w)*25),Math.floor(rng(w)*20));return w}
function candidates(w,n){return w.people.filter(p=>p.alive&&p.id!==n.id)}
function score(w,n,a){const q=n.needs,t=n.traits,h=w.hour;switch(a){case 'sleep':return (100-q.energy)*1.5+(h>=22||h<7?60:0);case 'eat':return q.hunger*1.6+(n.money>=w.market.food?5:-20);case 'work':return (h>=8&&h<=18?35:-25)+(n.money<25?40:0)+(n.debt>0?20:0)+t.discipline*.25-q.stress*.3-q.hunger*.3;case 'rest':return (100-q.energy)*.7+q.stress*.55;case 'socialize':return (100-q.social)*.75+t.sociability*.45;case 'visit':return (100-q.social)*.55+t.openness*.25;case 'borrow':return n.money<15?60+n.debt*.03-t.pride*.3:0;case 'repay':return n.debt>0&&n.money>25?45+t.discipline*.25:0;case 'trade':return n.money>45?12+t.risk*.25:0;case 'leisure':return 22+q.stress*.3+t.openness*.15;default:return 0}}
const ACTIONS=['sleep','eat','work','rest','socialize','visit','borrow','repay','trade','leisure'];
function choose(w,n){const scores=ACTIONS.map(a=>Math.max(0,score(w,n,a)+(rng(w)-.5)*15));const max=Math.max(...scores),weights=scores.map(v=>Math.exp((v-max)/15));let r=rng(w)*weights.reduce((a,b)=>a+b,0);for(let i=0;i<weights.length;i++)if((r-=weights[i])<=0)return ACTIONS[i];return 'rest'}
function reactToNews(w,listener,e){if(!['inheritance','conflict','loan'].includes(e.type))return;const actors=e.actors.map(id=>person(w,id)).filter(n=>n?.alive&&n.id!==listener.id);for(const actor of actors){const r=relation(w,listener,actor);const sympathy=listener.family.includes(actor.id)||r.affinity>=65;changeRel(w,listener,actor,sympathy?2:-3,sympathy?2:-2,sympathy?-1:3,e.id)}if(e.actors.includes(listener.id))listener.needs.stress=clamp(listener.needs.stress+5)}
function meet(w,a,b){if(!b||!b.alive||a.id===b.id)return;const r=relation(w,a,b);a.lastContact[b.id]=w.day;b.lastContact[a.id]=w.day;const known=a.memory.filter(m=>!b.memory.some(x=>x.eventId===m.eventId));if(known.length&&roll(w,.22+a.traits.sociability/500)){const m=pick(w,known.slice(0,12)),e=w.events.find(x=>x.id===m.eventId);if(e&&learn(w,b,e,'heard',a.id)){w.metrics.rumors++;reactToNews(w,b,e)}}const friendly=roll(w,clamp((r.affinity+a.traits.kindness+b.traits.kindness)/280,.1,.9));if(roll(w,.16)){const e=addEvent(w,friendly?'friendship':'conflict',[a,b],{},[a,b]);changeRel(w,a,b,friendly?3:-4,friendly?4:-4,friendly?-2:6,e.id)}a.needs.social=clamp(a.needs.social+12);b.needs.social=clamp(b.needs.social+8)}
function act(w,n,a){const q=n.needs,others=candidates(w,n);n.lastAction=a;n.actionCounts[a]=(n.actionCounts[a]||0)+1;w.metrics.decisions++;switch(a){case 'sleep':n.place='Ev';q.energy=clamp(q.energy+29);q.stress=clamp(q.stress-7);break;case 'eat':if(n.money>=w.market.food){n.money-=w.market.food;q.hunger=clamp(q.hunger-48)}else q.hunger=clamp(q.hunger-6);break;case 'work':n.place=n.job==='Çiftçi'?'Çiftlik':n.job==='Bankacı'?'Banka':n.job==='Fırıncı'?'Fırın':n.job==='Eczacı'?'Eczane':n.job==='Demirci'?'Demirci':'Meydan';{const pay=Math.max(1,Math.round(w.market.wage*(.6+n.traits.discipline/200)));n.money+=pay;q.energy=clamp(q.energy-10);q.hunger=clamp(q.hunger+7);q.stress=clamp(q.stress+3)}break;case 'rest':n.place='Ev';q.energy=clamp(q.energy+16);q.stress=clamp(q.stress-9);break;case 'socialize':case 'visit':{const b=others.length?pick(w,others):null;if(b){n.place=b.place;meet(w,n,b)}}break;case 'borrow':{const opts=others.filter(b=>b.money>18&&(n.creditor===null||n.creditor===b.id)).sort((a,b)=>relation(w,n,b).trust-relation(w,n,a).trust);const b=opts[0];if(!b)break;const r=relation(w,n,b),accepted=roll(w,clamp((r.trust+b.traits.kindness-n.traits.pride*.3)/140,.04,.9));if(accepted){const amount=Math.min(15,Math.floor(b.money*.2));if(amount<=0)break;b.money-=amount;n.money+=amount;n.debt+=amount;n.creditor=b.id;w.metrics.loans++;const e=addEvent(w,'loan',[n,b],{amount});changeRel(w,n,b,2,1,0,e.id)}else{const e=addEvent(w,'refusal',[n,b]);changeRel(w,n,b,-2,-2,2,e.id)}}break;case 'repay':{const b=person(w,n.creditor);if(b&&b.alive&&n.debt>0){const amount=Math.min(n.debt,Math.max(1,Math.floor(n.money*.2)));n.money-=amount;n.debt-=amount;b.money+=amount;const e=addEvent(w,'repayment',[n,b],{amount});changeRel(w,n,b,4,2,-2,e.id);if(!n.debt)n.creditor=null}}break;case 'trade':if(n.money>55&&roll(w,.12)){const asset=pick(w,['Küçük arsa','At','Tezgâh']);n.money-=35;n.assets.push(asset);addEvent(w,'purchase',[n],{asset})}break;case 'leisure':n.place=pick(w,['Ev','Meydan','Saloon']);q.stress=clamp(q.stress-5);q.energy=clamp(q.energy-3);break}}
function dayEnd(w){w.market.prosperity=clamp(w.market.prosperity+(rng(w)-.5)*4,15,90);w.market.wage=Math.max(2,Math.round(3+w.market.prosperity/25));w.market.food=Math.max(1,Math.round(2+(70-w.market.prosperity)/30));for(const n of w.people.filter(x=>x.alive)){if(n.debt>0&&roll(w,.12)){n.debt+=Math.max(1,Math.ceil(n.debt*.01));n.needs.stress=clamp(n.needs.stress+3)}if(n.money<5)n.needs.stress=clamp(n.needs.stress+4);if(n.needs.hunger>85){n.needs.health=clamp(n.needs.health-3);n.needs.stress=clamp(n.needs.stress+3)}else n.needs.health=clamp(n.needs.health+1);if(n.needs.health<35&&roll(w,.08)){addEvent(w,'illness',[n]);n.needs.health=clamp(n.needs.health-7)}if(n.needs.health>60&&roll(w,.01))addEvent(w,'recovery',[n]);if(n.debt>n.money*5&&n.assets.length&&roll(w,.025)){n.assets.pop();n.debt=Math.max(0,n.debt-35);addEvent(w,'bankruptcy',[n])}if(n.age>=65&&roll(w,Math.min(.0015,(n.age-60)/25000))){n.alive=false;w.metrics.deaths++;const e=addEvent(w,'death',[n]);const heir=person(w,n.partner)||person(w,n.children[0])||person(w,n.family[0]);if(heir&&heir.alive){heir.money+=n.money;heir.assets.push(...n.assets);n.money=0;n.assets=[];learn(w,heir,e,'witness')}}}if(w.people.length<200){const adults=w.people.filter(n=>n.alive&&n.age>=18&&n.age<=45&&n.partner!==null);for(const n of adults){if(n.id>n.partner)continue;const partner=person(w,n.partner);if(!partner?.alive)continue;if(roll(w,.0006)){const child=makePerson(w,w.nextId++,pick(w,NAMES),n.last,0,'Çocuk');child.parents=[n.id,partner.id];child.family=[n.id,partner.id];n.children.push(child.id);partner.children.push(child.id);n.family.push(child.id);partner.family.push(child.id);w.people.push(child);changeRel(w,n,child,40,45);changeRel(w,partner,child,40,45);w.metrics.births++;addEvent(w,'birth',[n,child],{},[n,partner])}}}if(w.day%365===0)for(const n of w.people)n.age++}
function tick(w){w.hour++;if(w.hour===24){w.hour=0;w.day++}for(const n of w.people){if(!n.alive)continue;const q=n.needs;q.hunger=clamp(q.hunger+3);q.energy=clamp(q.energy-2);q.social=clamp(q.social-2);if(q.hunger>75||q.energy<20)q.stress=clamp(q.stress+2);if(w.hour>=22||w.hour<7)n.place='Ev';act(w,n,choose(w,n))}if(w.hour===18)dayEnd(w);return w}
function advance(w,hours){for(let i=0;i<hours;i++)tick(w);return w}
const TOPICS=['selam','iş','geçmiş','aile','ilişkiler','haber','borç','miras','kasaba'];
function talk(w,n,topic){if(!n?.alive)return 'Bu kişiyle konuşamazsın.';const known=n.memory.map(m=>({m,e:w.events.find(e=>e.id===m.eventId)})).filter(x=>x.e);const trust=n.lastDialogue?.trust??35;let answer='';switch(topic){case 'selam':answer=pick(w,[`Selam. ${n.place} tarafındayım.`,`Merhaba. ${n.needs.energy<35?'Bugün biraz yorgunum.':'Nasıl gidiyor?'}`,`İyi günler. ${n.needs.stress>65?'Aklım biraz meşgul.':'Kasabada işler sürüyor.'}`]);break;case 'iş':answer=`${n.job} olarak çalışıyorum. ${n.money<12?'Bu aralar geçinmek kolay değil.':n.needs.energy<35?'Bugün epey yoruldum.':'İşler devam ediyor.'}`;break;case 'geçmiş':{const e=known.find(x=>x.e.day<1);answer=e&&n.traits.openness+trust>90?`${textEvent(w,e.e)} ${e.m.source==='witness'?'Bunu yaşadım.':'Bana böyle anlatıldı.'}`:`${n.age} yaşındayım, ${n.job.toLocaleLowerCase('tr-TR')} olarak çalışıyorum. Geçmişimi hemen herkese anlatmam.`;break}case 'aile':answer=n.family.length?`Ailemden ${n.family.slice(0,3).map(id=>name(w,id)).join(', ')} burada. ${n.partner!==null?`Eşim ${name(w,n.partner)}.`:''}`:'Burada yakın ailem yok.';break;case 'ilişkiler':{const links=w.people.filter(p=>p.alive&&p.id!==n.id&&w.relations[pair(n,p)]).sort((a,b)=>relation(w,n,b).affinity-relation(w,n,a).affinity);const p=links[0];answer=p?`${p.name} ile ${relation(w,n,p).affinity>65?'yakınız':relation(w,n,p).affinity<30?'aramız açık':'tanışıyoruz'}.`:'Kasabada henüz yakın olduğum kimse yok.';break}case 'haber':{const item=known.find(x=>x.e.day>=1&&x.e.type!=='gossip');answer=item?`${textEvent(w,item.e)} ${item.m.source==='witness'?'Buna kendim tanık oldum.':item.m.source==='player'?'Bunu senden duydum; doğruluğunu bilmiyorum.':`${name(w,item.m.from)} adlı kişiden duydum; doğruluğunu bilmiyorum.`}`:'Yeni bir haber duymadım.';break}case 'borç':answer=n.debt>0&&n.traits.openness+trust>95?`Şu anda ${n.debt}$ borcum var.`:n.debt>0?'Mali durumum hakkında konuşmak istemiyorum.':'Borcumla ilgili anlatacak bir şey yok.';break;case 'miras':{const item=known.find(x=>x.e.type==='inheritance');answer=item?`${textEvent(w,item.e)} ${item.m.source==='witness'?'O olayın içindeydim.':'Bunu başkasından duydum.'}`:'Miras meselesi hakkında bilgim yok.';break}case 'kasaba':answer=`Kasabada ${w.people.filter(x=>x.alive).length} kişi yaşıyor. ${w.market.prosperity<40?'İşler son zamanlarda zor.':'Hayat devam ediyor.'}`;break;default:answer='Bu konuda söyleyecek bir şeyim yok.'}n.lastDialogue={day:w.day,topic,trust:clamp(trust+1)};return `${n.name}: “${answer}”`}
const PLAYER_CHOICES=['help','ask_secret','share_news','confront'];
function playerChoice(w,targetId,choice,otherId=null,eventId=null){
 const target=person(w,targetId);
 if(!target?.alive)return{ok:false,message:'Bu kişiyle artık etkileşime geçilemez.'};
 if(!PLAYER_CHOICES.includes(choice))return{ok:false,message:'Bilinmeyen seçim.'};
 if(choice==='help'){
  const amount=10;
  if(w.playerHelpDays?.[target.id]===w.day)return{ok:false,message:'Bu kişiye bugün zaten yardım ettin. Yarın tekrar deneyebilirsin.'};
  if((w.playerMoney??50)<amount)return{ok:false,message:'Yardım etmek için en az 10$ gerekli.'};
  (w.playerHelpDays||(w.playerHelpDays={}))[target.id]=w.day;
  w.playerMoney=(w.playerMoney??50)-amount;
  target.money+=amount;target.needs.stress=clamp(target.needs.stress-8);
  const e=addEvent(w,'help',[target],{amount,player:true},[target]);
  target.playerTrust=clamp((target.playerTrust??40)+12);
  return{ok:true,message:`${target.name} yardımını kabul etti. 10$ aldı; sana güveni arttı.`,eventId:e.id};
 }
 if(choice==='ask_secret'){
  const known=target.memory.map(m=>w.events.find(e=>e.id===m.eventId)).filter(e=>e&&['inheritance','loan','conflict','secret'].includes(e.type));
  const secret=known[0];
  if(!secret)return{ok:true,message:`${target.name} paylaşabileceği bir sır bilmediğini söyledi.`};
  if((w.playerKnowledge||[]).includes(secret.id))return{ok:true,message:`${target.name} bu olayı sana daha önce anlatmıştı.`,eventId:secret.id};
  const chance=clamp(((target.playerTrust??40)+target.traits.openness-target.traits.pride*.35)/170,.05,.9);
  if(!roll(w,chance)){target.playerTrust=clamp((target.playerTrust??40)-2);return{ok:true,message:`${target.name} sırrını paylaşmak istemedi. Güveni biraz azaldı.`}};
  w.playerKnowledge=w.playerKnowledge||[];w.playerKnowledge.push(secret.id);
  target.playerTrust=clamp((target.playerTrust??40)+4);
  return{ok:true,message:`${target.name} sana anlattı: ${textEvent(w,secret)}`,eventId:secret.id};
 }
 if(choice==='share_news'){
  const ids=w.playerKnowledge||[];
  const event=w.events.find(e=>e.id===eventId&&ids.includes(e.id));
  if(!event)return{ok:false,message:'Paylaşmak için bildiğin bir haber seç.'};
  if(target.memory.some(m=>m.eventId===event.id))return{ok:true,message:`${target.name} bu haberi zaten biliyor.`};
  if(!learn(w,target,event,'player',null))return{ok:true,message:`${target.name} bu haberi zaten biliyor.`};
  w.metrics.rumors++;
  reactToNews(w,target,event);
  const gossip=addEvent(w,'gossip',[target],{about:event.id,player:true},[target]);
  if(event.actors.includes(target.id))target.playerTrust=clamp((target.playerTrust??40)-8);
  return{ok:true,message:`${target.name} haberi öğrendi. Bu olayda adı geçiyorsa sana güveni azaldı.`,eventId:gossip.id};
 }
 const known=target.memory.map(m=>w.events.find(e=>e.id===m.eventId)).filter(e=>e&&e.type==='inheritance');
 if(!known.length)return{ok:true,message:`${target.name} yüzleşeceğiniz bir miras meselesi bilmediğini söyledi.`};
 const event=known[0],opponent=event.actors.map(id=>person(w,id)).find(n=>n?.alive&&n.id!==target.id);
 if(!opponent)return{ok:true,message:'Anlaşmazlığın diğer tarafı artık burada değil.'};
 const success=roll(w,clamp(((target.playerTrust??40)+target.traits.kindness-opponent.traits.pride*.3)/170,.1,.85));
 const outcome=addEvent(w,success?'friendship':'conflict',[target,opponent],{player:true,about:event.id},[target,opponent]);
 changeRel(w,target,opponent,success?7:-5,success?5:-4,success?-5:8,outcome.id);
 target.playerTrust=clamp((target.playerTrust??40)+(success?5:-3));
 return{ok:true,message:success?`${target.name} ile ${opponent.name} konuşup aralarını yumuşattı.`:`Yüzleşme ${target.name} ile ${opponent.name} arasındaki gerilimi artırdı.`,eventId:outcome.id};
}
function validate(w){const issues=[],ids=new Set(w.people.map(n=>n.id)),events=new Set(w.events.map(e=>e.id));if(ids.size!==w.people.length)issues.push('Yinelenen NPC kimliği');for(const n of w.people){if(!Number.isFinite(n.money)||n.money<0)issues.push(`${n.id}: geçersiz para`);if(n.debt<0)issues.push(`${n.id}: negatif borç`);for(const id of [...n.parents,...n.children,...n.family])if(!ids.has(id))issues.push(`${n.id}: geçersiz aile bağı`);for(const m of n.memory)if(!events.has(m.eventId))issues.push(`${n.id}: geçersiz hafıza`);if(n.partner!==null&&!ids.has(n.partner))issues.push(`${n.id}: geçersiz eş`)}if(w.playerMoney!==undefined&&(!Number.isFinite(w.playerMoney)||w.playerMoney<0))issues.push('Geçersiz oyuncu parası');if(w.playerKnowledge!==undefined){if(!Array.isArray(w.playerKnowledge))issues.push('Geçersiz oyuncu haberleri');else for(const id of w.playerKnowledge)if(!events.has(id))issues.push('Geçersiz oyuncu haberi')}if(w.playerHelpDays!==undefined){if(!w.playerHelpDays||typeof w.playerHelpDays!=='object'||Array.isArray(w.playerHelpDays))issues.push('Geçersiz yardım geçmişi');else for(const [id,day] of Object.entries(w.playerHelpDays))if(!ids.has(Number(id))||!Number.isInteger(day)||day<1||day>w.day)issues.push('Geçersiz yardım günü')}for(const e of w.events)for(const id of e.actors)if(!ids.has(id))issues.push(`${e.id}: geçersiz aktör`);return issues}
function stats(w){return{day:w.day,population:w.people.filter(n=>n.alive).length,events:w.events.length,...w.metrics}}
return{create,tick,advance,talk,playerChoice,PLAYER_CHOICES,validate,stats,person,relation,textEvent,TOPICS,PLACES,ACTIONS,learn,addEvent,changeRel};})();
if(typeof module!=='undefined')module.exports=Ashford;
