'use strict';const assert=require('node:assert/strict'),A=require('./engine.js');
function test(name,fn){try{fn();console.log('PASS '+name)}catch(e){console.error('FAIL '+name+': '+e.stack);process.exitCode=1}}
test('10 NPC and shared families',()=>{const w=A.create(12345);assert.equal(w.people.length,10);assert.equal(w.people[0].partner,5);assert.ok(w.people[6].parents.includes(0));assert.deepEqual(A.validate(w),[])});
test('deterministic 30-day simulation',()=>{const a=A.create(42),b=A.create(42);A.advance(a,720);A.advance(b,720);assert.equal(JSON.stringify(a),JSON.stringify(b));assert.deepEqual(A.validate(a),[])});
test('100-day memory and relationship consistency',()=>{const w=A.create(345);A.advance(w,2400);assert.deepEqual(A.validate(w),[]);assert.ok(w.metrics.decisions>=24000);assert.ok(w.events.length>0);assert.ok(w.people.some(n=>n.memory.length>0))});
test('no omniscient inheritance dialogue',()=>{const w=A.create(10);const outsider=w.people[7];assert.ok(!outsider.memory.some(m=>w.events.find(e=>e.id===m.eventId)?.type==='inheritance'));assert.match(A.talk(w,outsider,'miras'),/bilgim yok/)});
test('1-year economy and long simulation',()=>{const w=A.create(77);A.advance(w,8760);assert.deepEqual(A.validate(w),[]);assert.ok(w.people.every(n=>n.money>=0&&n.debt>=0));assert.ok(w.day>=365)});
test('10-year lifecycle and capped memory',()=>{const w=A.create(99);A.advance(w,87600);assert.deepEqual(A.validate(w),[]);assert.ok(w.people.every(n=>n.memory.length<=65));assert.ok(w.events.length<=5000)});
test('100 NPC 100-day scaling',()=>{const w=A.create(12,100);A.advance(w,2400);assert.deepEqual(A.validate(w),[]);assert.ok(w.metrics.decisions>=240000)});
test('JSON save/load roundtrip',()=>{const w=A.create(2026);A.advance(w,120);const restored=JSON.parse(JSON.stringify(w));assert.deepEqual(A.validate(restored),[]);assert.deepEqual(restored,w)});

test('player gossip shares selected knowledge once and survives save',()=>{const w=A.create(12345),source=w.people[0],recipient=w.people[2];source.playerTrust=100;source.traits.openness=100;source.traits.pride=0;const learned=A.playerChoice(w,source.id,'ask_secret');assert.equal(learned.ok,true);assert.ok(w.playerKnowledge.includes(learned.eventId));const before=w.metrics.rumors;const shared=A.playerChoice(w,recipient.id,'share_news',null,learned.eventId);assert.equal(shared.ok,true);assert.equal(w.metrics.rumors,before+1);assert.ok(recipient.memory.some(m=>m.eventId===learned.eventId&&m.source==='player'&&m.from===null));const again=A.playerChoice(w,recipient.id,'share_news',null,learned.eventId);assert.match(again.message,/zaten biliyor/);assert.equal(w.metrics.rumors,before+1);const restored=JSON.parse(JSON.stringify(w));assert.deepEqual(A.validate(restored),[]);assert.deepEqual(restored.playerKnowledge,w.playerKnowledge)});
test('player choices reject unlearned gossip without changing state',()=>{const w=A.create(12345),before=JSON.stringify(w);const result=A.playerChoice(w,2,'share_news',null,w.events[0].id);assert.equal(result.ok,false);assert.equal(JSON.stringify(w),before)});

test('news changes recipient relations and persists after save',()=>{const w=A.create(12345),source=w.people[0],recipient=w.people[2];source.playerTrust=100;source.traits.openness=100;source.traits.pride=0;const learned=A.playerChoice(w,source.id,'ask_secret');assert.ok(learned.eventId!==undefined);const before=A.relation(w,recipient,source).trust;const result=A.playerChoice(w,recipient.id,'share_news',null,learned.eventId);assert.equal(result.ok,true);assert.notEqual(A.relation(w,recipient,source).trust,before);assert.deepEqual(A.validate(JSON.parse(JSON.stringify(w))),[])});

test('daily help cooldown persists through JSON and resets next day',()=>{const w=A.create(12345),target=w.people[0],before=target.money;assert.equal(A.playerChoice(w,target.id,'help').ok,true);const saved=JSON.parse(JSON.stringify(w));assert.equal(A.playerChoice(saved,target.id,'help').ok,false);assert.equal(saved.people[0].money,before+10);A.advance(saved,24);assert.equal(A.playerChoice(saved,target.id,'help').ok,true);assert.deepEqual(A.validate(saved),[])});
test('insufficient funds do not consume daily help allowance',()=>{const w=A.create(12345);w.playerMoney=0;assert.equal(A.playerChoice(w,0,'help').ok,false);w.playerMoney=10;assert.equal(A.playerChoice(w,0,'help').ok,true);assert.equal(w.playerMoney,0);assert.deepEqual(A.validate(w),[])});

test('NPC secrets require trust and openness to spread',()=>{const w=A.create(12345),a=w.people[0],b=w.people[2];const secret=A.addEvent(w,'secret',[a,w.people[1]],{},[a]);const r=A.relation(w,a,b);r.trust=64;a.traits.openness=100;assert.ok(!A.shareableNews(w,a,b).some(x=>x.e.id===secret.id));r.trust=65;assert.ok(A.shareableNews(w,a,b).some(x=>x.e.id===secret.id));a.traits.openness=39;assert.ok(!A.shareableNews(w,a,b).some(x=>x.e.id===secret.id));assert.deepEqual(A.validate(w),[])});
test('NPC gossip event is not recursively shared',()=>{const w=A.create(12345),a=w.people[0],b=w.people[2];const gossip=A.addEvent(w,'gossip',[a],{about:w.events[0].id},[a]);assert.ok(!A.shareableNews(w,a,b).some(x=>x.e.id===gossip.id))});

test('ask secret skips events already known by player',()=>{const w=A.create(12345),n=w.people[0];n.playerTrust=100;n.traits.openness=100;n.traits.pride=0;const first=w.events[0];const second=A.addEvent(w,'conflict',[n,w.people[2]],{},[n]);w.playerKnowledge=[first.id];const result=A.playerChoice(w,n.id,'ask_secret');assert.equal(result.ok,true);assert.equal(result.eventId,second.id);assert.ok(w.playerKnowledge.includes(second.id));assert.deepEqual(A.validate(w),[])});
test('NPC does not reveal secret in ordinary news dialogue without trust',()=>{const w=A.create(12345),n=w.people[2];A.addEvent(w,'secret',[n,w.people[3]],{},[n]);n.playerTrust=40;n.traits.openness=100;assert.match(A.talk(w,n,'haber'),/Yeni bir haber duymadım/);n.playerTrust=65;assert.match(A.talk(w,n,'haber'),/sırrını/);assert.deepEqual(A.validate(w),[])});
