'use strict';const assert=require('node:assert/strict'),A=require('./engine.js');
function test(name,fn){try{fn();console.log('PASS '+name)}catch(e){console.error('FAIL '+name+': '+e.stack);process.exitCode=1}}
test('10 NPC and shared families',()=>{const w=A.create(12345);assert.equal(w.people.length,10);assert.equal(w.people[0].partner,5);assert.ok(w.people[6].parents.includes(0));assert.deepEqual(A.validate(w),[])});
test('deterministic 30-day simulation',()=>{const a=A.create(42),b=A.create(42);A.advance(a,720);A.advance(b,720);assert.equal(JSON.stringify(a),JSON.stringify(b));assert.deepEqual(A.validate(a),[])});
test('100-day memory and relationship consistency',()=>{const w=A.create(345);A.advance(w,2400);assert.deepEqual(A.validate(w),[]);assert.ok(w.metrics.decisions>=24000);assert.ok(w.events.length>0);assert.ok(w.people.some(n=>n.memory.length>0))});
test('no omniscient inheritance dialogue',()=>{const w=A.create(10);const outsider=w.people[7];assert.ok(!outsider.memory.some(m=>w.events.find(e=>e.id===m.eventId)?.type==='inheritance'));assert.match(A.talk(w,outsider,'miras'),/bilgim yok/)});
test('1-year economy and long simulation',()=>{const w=A.create(77);A.advance(w,8760);assert.deepEqual(A.validate(w),[]);assert.ok(w.people.every(n=>n.money>=0&&n.debt>=0));assert.ok(w.day>=365)});
test('10-year lifecycle and capped memory',()=>{const w=A.create(99);A.advance(w,87600);assert.deepEqual(A.validate(w),[]);assert.ok(w.people.every(n=>n.memory.length<=65));assert.ok(w.events.length<=5000)});
test('100 NPC 100-day scaling',()=>{const w=A.create(12,100);A.advance(w,2400);assert.deepEqual(A.validate(w),[]);assert.ok(w.metrics.decisions>=240000)});
test('JSON save/load roundtrip',()=>{const w=A.create(2026);A.advance(w,120);const restored=JSON.parse(JSON.stringify(w));assert.deepEqual(A.validate(restored),[]);assert.deepEqual(restored,w)});

test('player gossip shares selected knowledge once and survives save',()=>{const w=A.create(12345),source=w.people[0],recipient=w.people[2];source.playerTrust=100;source.traits.openness=100;source.traits.pride=0;const learned=A.playerChoice(w,source.id,'ask_secret');assert.equal(learned.ok,true);assert.ok(w.playerKnowledge.includes(learned.eventId));const before=w.metrics.rumors;const shared=A.playerChoice(w,recipient.id,'share_news',null,learned.eventId);assert.equal(shared.ok,true);assert.equal(w.metrics.rumors,before+1);assert.ok(recipient.memory.some(m=>m.eventId===learned.eventId&&m.source==='player'&&m.from===null));const again=A.playerChoice(w,recipient.id,'share_news',null,learned.eventId);assert.match(again.message,/zaten biliyor/);assert.equal(w.metrics.rumors,before+1);const restored=JSON.parse(JSON.stringify(w));assert.deepEqual(A.validate(restored),[]);assert.deepEqual(restored.playerKnowledge,w.playerKnowledge)});
test('player choices reject unlearned gossip without changing state',()=>{const w=A.create(12345),before=JSON.stringify(w);const result=A.playerChoice(w,2,'share_news',null,w.events[0].id);assert.equal(result.ok,false);assert.equal(JSON.stringify(w),before)});

test('news changes recipient relations and persists after save',()=>{const w=A.create(12345),source=w.people[0],recipient=w.people[2];source.playerTrust=100;source.traits.openness=100;source.traits.pride=0;const learned=A.playerChoice(w,source.id,'ask_secret');assert.ok(learned.eventId!==undefined);const before=A.relation(w,recipient,source).trust;const result=A.playerChoice(w,recipient.id,'share_news',null,learned.eventId);assert.equal(result.ok,true);assert.notEqual(A.relation(w,recipient,source).trust,before);assert.deepEqual(A.validate(JSON.parse(JSON.stringify(w))),[])});
